name: Flask Web Application (Moscow Time)

on:
  push:
    branches: [ "lab3", "master" ]
    paths: [ "app_python" ]
  pull_request:
    branches: [ "master" ]
    paths: [ "app_python" ]


permissions:
  contents: read

jobs:
  security:
    name: Check for vulnerabilities
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.9@master@4a528b5c534bb771b6e3772656a8e0e9dc902f8b
        with:
          command: test  
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build:
    needs: [security]
    name: Build & Test
    timeout-minutes: 10
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4.2.2@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Python
        uses: actions/setup-python@v5.4.0@42375524e23c412d93fb67b49958b491fce71c38
        with:
          python-version: '3.13'
          architecture: 'x64'
          cache: 'pip'

      - name: Install dependencies
        working-directory: app_python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint code
        working-directory: app_python
        run: |
          flake8 tests app.py
          pylint tests app.py

      - name: Test with pytest
        working-directory: app_python
        run: pytest tests

  docker:
    needs: [security, build] 
    name: Build & Push Docker images
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.3.0@53851d14592bedcffcf25ea515637cff71ef929a

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0@6524bf65af31da8d45b59e8c27de4bd072b392f5

      - name: Build and push normal image
        uses: docker/build-push-action@v6.13.0@ca877d9245402d1537745e0e356eab47c3520991
        with:
          push: true
          context: app_python  
          tags: ${{ vars.DOCKERHUB_USERNAME }}/app_python:app_python-prod-ci-1.0.0
          cache-from: type=gha,scope=container
          cache-to: type=gha,mode=max,scope=container

      - name: Build and push distroless image
        uses: docker/build-push-action@v6.13.0@ca877d9245402d1537745e0e356eab47c3520991
        with:
          push: true
          context: app_python  
          tags: ${{ vars.DOCKERHUB_USERNAME }}/app_python:app_python-distroless-prod-ci-1.0.0
          cache-from: type=gha,scope=container
          cache-to: type=gha,mode=max,scope=container